{% set version = "1.67.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/{{ filename }}
  sha256: 2684c972994ee57fc5632e03bf044746f6eb45d4920c343937a465fd67a5adba

build:
  number: 0
  features:
    - vc9               # [win and py27]
    - vc14              # [win and py>=35]

requirements:
  build:
    - toolchain
    - python
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - vc 9              # [win and py27]
    - vc 14             # [win and py>=35]
    - boost-cpp {{ version }}

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - vc 9              # [win and py27]
    - vc 14             # [win and py>=35]
    - boost-cpp {{ version }}

test:
  commands:
    # Verify Python headers are installed.
    - test -f $PREFIX/include/boost/python.hpp                 # [unix]
    - test -d $PREFIX/include/boost/python                     # [unix]
    - if not exist %LIBRARY_INC%\\boost\\python.hpp exit 1     # [win]
    - if not exist %LIBRARY_INC%\\boost\\python exit 1         # [win]

    # Verify libraries.
    {% set py3k_suffix = "3" if py3k else "" %}
    {% set boost_libs = [
            "python%s" % py3k_suffix,
            "numpy%s" % py3k_suffix
    ] %}
    {% for each_boost_lib in boost_libs %}
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.a                                                 # [unix]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}${SHLIB_EXT}                                       # [unix]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}.dll exit 1                          # [win]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}.lib exit 1                          # [win]
    - if not exist %PREFIX%\\Library\\lib\\libboost_{{ each_boost_lib }}.lib exit 1                       # [win]
    {% endfor %}
    - conda inspect linkages -p $PREFIX boost  # [not win]
    - conda inspect objects -p $PREFIX boost  # [osx]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  license_file: LICENSE_1_0.txt
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - jschueller
    - scopatz
    - isuruf
