{% set version = "1.63.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: {{ version }}

source:
  fn:  {{ filename }}
  #url: http://sourceforge.net/projects/boost/files/boost/{{ version }}/{{ filename }}
  url: https://github.com/conda-forge/boost-feedstock/releases/download/sources/{{ filename }}
  sha256: beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0
  patches:
    - boost_python_pr110.patch

build:
  number: 7
  features:
    - vc9               # [win and py27]
    - vc10              # [win and py34]
    - vc14              # [win and py>=35]

requirements:
  build:
    - toolchain
    - python
    - numpy x.x
    - vc 9              # [win and py27]
    - vc 10             # [win and py34]
    - vc 14             # [win and py>=35]
    - boost-cpp {{ version }}

  run:
    - python
    - numpy x.x
    - vc 9              # [win and py27]
    - vc 10             # [win and py34]
    - vc 14             # [win and py>=35]
    - boost-cpp {{ version }}

test:
  commands:
    # Verify Python headers are installed.
    - test -f $PREFIX/include/boost/python.hpp                 # [unix]
    - test -d $PREFIX/include/boost/python                     # [unix]
    - if not exist %LIBRARY_INC%\\boost\\python.hpp exit 1     # [win]
    - if not exist %LIBRARY_INC%\\boost\\python exit 1         # [win]

    # Verify libraries.
    {% set win_vstr = "_".join(version.split(".")[:2]) %}
    {% set boost_libs = [
            "python",
            "numpy"
    ] %}
    {% for each_boost_lib in boost_libs %}
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.a                                                 # [unix]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.dylib                                             # [osx]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.so                                                # [linux]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.dll exit 1   # [win and py27]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.dll exit 1  # [win and py34]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.dll exit 1  # [win and py >= 35]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.lib exit 1   # [win and py27]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.lib exit 1  # [win and py34]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.lib exit 1  # [win and py >= 35]
    {% endfor %}
    - conda inspect linkages -p $PREFIX boost  # [not win]
    - conda inspect objects -p $PREFIX boost  # [osx]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - jschueller
    - scopatz
    - isuruf
