appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eS2Gu9tuLwZq6ZDFEKSMN53vgHdiQ+5hBT5DuY1TJAbPP4uQFCaoyaCv7nz8Jd4ddSn4YMsJ8EL7Lv/L7eA7lY7Wj7pJeZ1L0Q+4r1nE9QUU+m2FDy5WUFGD83LKfzkJb76SpGOIjZp82yJnBZgP90cH5HZ9HvDSsnyfHfc/Z+OhnI362mrgZVwOk4UM0uCtNuWH7It7xvPTQypXi+rpDxxFxMilPsC8D6Hycx+UMne7slY4MJj37bRmMwyJbl5PziKnOZ0aI57Knb2nLHfNFk08846CnXD6mlX0yxXE56PNTGyUq7/usHeKXA7mnYuVZS3Y+2O3N3q+jslBf2vCE5PxppYsI/J3SG0vlqczf+byoqi6pJadQFhXv6nfbtPGk974n+ayMh35HVcwiRo4eDjY68V8EAq0BQ6fdIrvEkdvxoB6v/WdRuULhLFnGV8R/fQzkv5L/7BiNJPmQoW7zB6AP8LA/9BRHE7rUIJCO/eyWLE2EfiTZ+ndTiKE7OvqnK8o9DJ5G53WpVN4xJJ+7A47a7ye8bniv100/Zba02DSLyZyeV9Yr1MCp3HCnGmRIXicoFSAtTVhKKRrfzVNlh067ObQUBqfIh2ma8DbWo4U5UEP23o1VLH9UdRBOoDlvh0EoqeNQKXnkHDFkwcFP56q66xyM12Vi4G9x/p6M7I=}
