bot:
  abi_migration_branches:
  - v1.90.x
  - v1.88.x
build_platform:
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- linux_64
- win_64
provider:
  linux_aarch64: default
  osx_arm64: default
test: native_and_emulated
workflow_settings:
  pagefile_size:
    - value: 16
      os: win
