azure:
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - v1.82.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
remote_ci_setup:
- conda-forge-ci-setup=4
- conda-build<3.28
test: native_and_emulated
